/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package icongetter.ui;

import java.util.LinkedList;
import java.util.List;
import java.util.regex.PatternSyntaxException;

import javax.swing.JFileChooser;
import javax.swing.SpinnerNumberModel;

import icongetter.bean.IconInfo;
import icongetter.core.BaiduEngine;
import icongetter.core.BingEngine;
import icongetter.core.Core;
import icongetter.core.GoogleEngine;
import icongetter.core.MyLog;
import icongetter.core.OnDoneListener;
import icongetter.core.SearchEngine;

/**
 *
 * @author Auggie Liang
 * 主要显示类
 */
public class MainUI extends javax.swing.JFrame implements PrintableUi,OnDoneListener{
    private boolean mIsDone;

    private String mSearchForword = "site:itunes.apple.com";
    
    private Core.IconWorker mIconWorker;

    /*＊搜索引擎信息**/
    private SearchEngine mSearchEngine = new GoogleEngine();

    private String[] engineList = { "Google", "Bing", "Baidu" };
    /** 保存路径*/
    private String mPath;
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        MyLog.init(this);
        tAreasearchForword.setText(mSearchForword);
        //默认设置默认值为3，范围[1,10]步长为1
        spinner.setModel( new SpinnerNumberModel(3, 1, 10, 1));
        engineChooser.setModel(new javax.swing.DefaultComboBoxModel(engineList));
        //未开始的时候不允许cancel
        btnCancel.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tAreaInput = new javax.swing.JTextArea();
        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAreaTaskInfo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        chooseFilePatch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tAreasearchForword = new javax.swing.JTextField();
        engineChooser = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tAreaInput.setColumns(20);
        tAreaInput.setRows(5);
        jScrollPane1.setViewportView(tAreaInput);

        btnStart.setText("开始搜索和下载");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel1.setText("输入应用名，换行隔开");

        spinner.setVerifyInputWhenFocusTarget(false);
        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });

        jLabel2.setText("单个图标下载个数");

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tAreaTaskInfo.setColumns(20);
        tAreaTaskInfo.setRows(5);
        jScrollPane2.setViewportView(tAreaTaskInfo);

        jLabel3.setText("任务信息");

        chooseFilePatch.setText("选择下载文件夹");
        chooseFilePatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFilePatchActionPerformed(evt);
            }
        });

        jLabel4.setText("搜索前缀");

        tAreasearchForword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAreasearchForwordActionPerformed(evt);
            }
        });

        engineChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineChooserActionPerformed(evt);
            }
        });

        jLabel5.setText("搜索引擎");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tAreasearchForword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(spinner))
                            .addComponent(chooseFilePatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(engineChooser, 0, 86, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(chooseFilePatch)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(engineChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAreasearchForword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** 取消操作*/
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if(mIconWorker != null ) {
            done();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**选择路径*/
    private void chooseFilePatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFilePatchActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            mPath = fileChooser.getSelectedFile().getPath();
            MyLog.i("选择的路径为-->"+mPath);
        }
    }//GEN-LAST:event_chooseFilePatchActionPerformed

    private void tAreasearchForwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAreasearchForwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAreasearchForwordActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
          String inputString = tAreaInput.getText();
        if(inputString == null ||inputString.equals("")){
            MyLog.i("输入为空！");
            return;
        }
        String[] iconNames = null;
        try{
            iconNames = inputString.split("\n");
        }catch(PatternSyntaxException exception){
            MyLog.i("输入格式错误!");
        }
        if(iconNames == null) return;
        List<IconInfo> iconInfos = new LinkedList<IconInfo>();
        for(String name : iconNames){
            name = name.replaceAll(" ", "");//把空格替换为空
            if(name.equals("")) continue;
            IconInfo iconInfo = new IconInfo();
            iconInfo.name = name;
            iconInfos.add(iconInfo);
        }
        if(!mIsDone){
            MyLog.i("开始搜索");
            mIconWorker = new Core.IconWorker(iconInfos, getSearchForward(),mPath,this,
                    Integer.valueOf(spinner.getValue().toString()), mSearchEngine);
            mIconWorker.setOnDoneListener(new OnDoneListener() {
                @Override
                public void done() {
                    MainUI.this.done();
                }
            });
            btnStart.setEnabled(false);
            mIsDone = true;
            mIconWorker.execute();
            btnCancel.setEnabled(true);
        }

    }//GEN-LAST:event_btnStartActionPerformed

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerStateChanged

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
      
    }//GEN-LAST:event_btnStartMouseClicked

    private void engineChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineChooserActionPerformed
        // TODO add your handling code here:
        //选择引擎
        System.out.println(evt.getActionCommand());
        System.out.println(engineChooser.getSelectedItem());
        String selectItem = engineChooser.getSelectedItem().toString();
        if(selectItem.equals(engineList[0])){//google 引擎
            mSearchEngine = new GoogleEngine();
        }else if(selectItem.equals(engineList[1])){//bing
            mSearchEngine = new BingEngine();
        }else if(selectItem.equals(engineList[2])){
            mSearchEngine = new BaiduEngine();
        }
    }//GEN-LAST:event_engineChooserActionPerformed

    /**获得搜索前缀*/
    public String getSearchForward(){
        String text = tAreasearchForword.getText();
        text = text.replaceAll(" ", "%20");
        if(!text.contains("%20")){
            text += "%20";
        }

        return text;
    }

    @Override
    public void done(){
        mIsDone = false;
        mIconWorker.getCore().cancel();
        mIconWorker.cancel(true);
        mIconWorker = null;
        btnStart.setEnabled(true);
        btnCancel.setEnabled(false);
    }
    /**
     * 打印到输出框
     * @param str 
     */
    @Override
    public void print(String str){
        tAreaTaskInfo.append(str);
    }

    @Override
    public void println(String str){
        tAreaTaskInfo.append(str + "\n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton chooseFilePatch;
    private javax.swing.JComboBox engineChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextArea tAreaInput;
    private javax.swing.JTextArea tAreaTaskInfo;
    private javax.swing.JTextField tAreasearchForword;
    // End of variables declaration//GEN-END:variables
}
